export const CREATE_DASHBOARD = 'CREATE_DASHBOARD';
export const CREATE_PANEL = 'CREATE_PANEL';
export const CREATE_FILTER = 'CREATE_FILTER';

export const EDIT_DASHBOARD = 'CREATE_DASHBOARD';
export const EDIT_PANEL = 'CREATE_PANEL';
export const EDIT_FILTER = 'CREATE_FILTER';
